### ISSUE TITLE
Selected/Non-Selected Font Colors should not be forced to be the same

### ISSUE THREAD

**Issue by inPhilly** [josshad/EHHorizontalSelectionView#7]
Depending on the background color for the control and the background color for the selected view, selected/non-selected font colors, in several cases, should not be forced to be the same. For example, I use a white control background and a dark selected background. So it would make most sense for me to use a dark font color for the Non-selected sections and a white font color for the selected section. However, there is currently no way to do this with the control.

**Comment by josshad** [comment]
Hello! 
Sorry for late response.

I add that functionality so now you can use the following methods:

* To change appearance for whole selectionView
`[_hSelView1 setAltTextColor:[UIColor orangeColor]];` 

* To change appearance for all cells of class
`[EHHorizontalLineViewCell updateAltTextColor:[UIColor colorWithHex:0xF181A2]];`

* For one cell in _- (EHHorizontalViewCell *)selectionView:(EHHorizontalSelectionView *)selectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath_
` cell.altTextColor = [UIColor blackColor];`
