### ISSUE TITLE
Unable to register in Swift 3

### ISSUE THREAD

**Issue by muzamilhassan1987** [josshad/EHHorizontalSelectionView#8]
I am getting this error when using swift 3

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle 
</Users/soomroshahid/Library/Developer/CoreSimulator/Devices/608B89C1-6BB2-4486-B747-4E8BCD976E8B/data/Containers/Bundle/Application/A0656148-9E39-4907-8D1B-3B965E8ACA70/SmartMart.app/Frameworks/EHHorizontalSelectionView.framework> (loaded)' with name 'EHHorizontalViewCell''

**Comment by josshad** [comment]
Fixed in 1.2.0

Example:
```
    @IBOutlet weak var hSelView: EHHorizontalSelectionView!
    var items = ["Living Room", "Kitchen", "Bathroom", "Balcony"]
    override func viewDidLoad() {
        super.viewDidLoad()
        hSelView.delegate = self

    }
    
    func numberOfItems(inHorizontalSelection hSelView: EHHorizontalSelectionView) -> UInt {
        return UInt(items.count)
    }
    
    func titleForItem(at index: UInt, forHorisontalSelection hSelView: EHHorizontalSelectionView) -> String? {
        return items[Int(index)]
    }
```
